version: "3.7"
services:
  halyard-backend:
    image: c6oio/halyard-demo-backend:$USER
    build:
      context: ./halyard-backend
  halyard-sockets:
    image: c6oio/halyard-demo-sockets:$USER
    build:
      context: ./halyard-sockets
  halyard-frontend:
    image: c6oio/halyard-demo-frontend:$USER
    build:
      context: ./halyard-frontend
  halyard-sails:
    image: c6oio/halyard-demo-sails:$USER
    build:
      context: ./halyard-sails
