apiVersion: v1
kind: Service
metadata:
  name: sample-project-frontend
  labels:
    app: sample-project
    component: frontend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: sample-project
    component: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-project-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-project-frontend
            port:
              number: 80
