apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-project-core-config
data:
  # These are here to demonstrate capturing config
  # values in using the environment features of czctl
  SAMPLE1_KEY: VALUE1
  SAMPLE2_KEY: VALUE2
  SAMPLE_PROJECT_VERSION: "Version Production"
  SAMPLE_PROJECT_API_PORT: "3000"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-project-core-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-project-core
  labels:
    app: sample-project
    component: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-project
      component: core
  template:
    metadata:
      labels:
        app: sample-project
        component: core
    spec:
      strategy:
        type: Recreate
      containers:
        - name: sample-project-core
          image: c6oio/sample-project-core
          imagePullPolicy: Always
          env:
            - name: SP_LEAF_URL
              value: http://sample-project-leaf:3010
            - name: SP_DB_URL
              value: mongodb://sample-project-database:27017/sample-project-database
          envFrom:
            - configMapRef:
                name: sample-project-core-config
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /usr/src/app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sample-project-core-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sample-project-core
  labels:
    app: sample-project
    component: core
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: sample-project
    component: core
