apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-project-database
  labels:
    app: sample-project
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-project
      component: database
  template:
    metadata:
      labels:
        app: sample-project
        component: database
    spec:
      containers:
        - name: mongodb-container
          image: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              value: sample-project-database
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: sample-project-database
  labels:
    app: sample-project
    component: database
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: sample-project
    component: database