apiVersion: apps/v1
kind: Deployment
metadata:
  name: halyard-backend
  labels:
    app: halyard
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: halyard
      component: backend
  template:
    metadata:
      labels:
        app: halyard
        component: backend
    spec:
      containers:
        - name: halyard-backend
          image: c6oio/halyard-demo-backend:latest
          imagePullPolicy: Always
          env:
            - name: HALYARD_ECHO
              value: http://halyard-echo:8080
            - name: HALYARD_DATABASE
              value: mongodb://halyard-database:27017/halyard-database
          envFrom:
            - configMapRef:
                name: halyard-backend-config
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: volume-test1
              mountPath: "/volumes/test1"
            - name: volume-test2
              mountPath: "/volumes/test2"
      volumes:
        - name: volume-test1
          persistentVolumeClaim:
            claimName: halyard-backend-claim1
        - name: volume-test2
          persistentVolumeClaim:
            claimName: halyard-backend-claim2