apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-project-leaf
  labels:
    app: sample-project
    component: leaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-project
      component: leaf
  template:
    metadata:
      labels:
        app: sample-project
        component: leaf
    spec:
      containers:
        - name: sample-project-leaf
          image: c6oio/sample-project-leaf
          imagePullPolicy: Always
          ports:
            - containerPort: 3010
              protocol: TCP
              name: http
            - containerPort: 3443
              protocol: TCP
              name: https
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: nginx-ssl
              readOnly: true
      volumes:
        - name: nginx-ssl
          secret:
            secretName: leaf-cert-tls
---
apiVersion: v1
kind: Service
metadata:
  name: sample-project-leaf
  labels:
    app: sample-project
    component: leaf
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3010
      targetPort: 3010
    - name: https
      protocol: TCP
      port: 3011
      targetPort: 3011
  selector:
    app: sample-project
    component: leaf
---
# Self-Signed Certificate for use by leaf service SSL listener.
# WARNING: Never do this in a real environment.  Use something like cert-manager instead.
apiVersion: v1
kind: Secret
metadata:
  name: leaf-cert-tls
  namespace: sample-project
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwRENDQWJpZ0F3SUJBZ0lSQUtGdUVuWTIzRUJERUM3eHJ4c1M4bVV3RFFZSktvWklodmNOQVFFTEJRQXcKQURBZ0Z3MHlNakExTWpReU1qQTBORGRhR0E4eU1UTTJNRFl5TWpFME1EUTBOMW93QURDQ0FTSXdEUVlKS29aSQpodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU9LdHJWY1h0RkRMYUxTUko2TTN0dmcrZXc0Unhqa1BHOXdiCkx2T21KUGhhR2xHS1NWZjdDRjBMMHljbzZwdnpGUTdOSkdlQncwNlNaNEJqK0FxbmNTR2FIQU9PYnR2NHlWQkIKTm9rZSt3ckY2ZzcvNy9pcHhVTkxlMDB4cEQ1eWczVmdsQ1htUWpxK1NsSVk0N1U5cHFrVHl0Z0cyV0NSMXRJWApRTk9PK1NHbG5HcWlRSHJWT3pHV1lKaE9QL3RIOW1IWVJ4NDBFMzAwalRsaGs5bzZYNXVFV3JiN0pxT2huS0NTCjVqSGtQbTRoVVRZMVI4aDRjdVJKUVErWmpQSGhiUHR1STl1Z3B5aEZWdXZjQ1RlRUw1aXJxSzRwbm80aEhRNnMKM2R3eHliYUp6azRMYVJHZTZJNTNmcG53bU9XMytWUUF5VkhsL3pnUlRXQXBjUjF4NjZrQ0F3RUFBYU5ETUVFdwpEZ1lEVlIwUEFRSC9CQVFEQWdXZ01Bd0dBMVVkRXdFQi93UUNNQUF3SVFZRFZSMFJBUUgvQkJjd0ZZSVRjMkZ0CmNHeGxMWEJ5YjJwbFkzUXRiR1ZoWmpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWh6TlBIQXVzYmtYSEN5b0kKTTByaE5BRWpwMENUUTRHdnpSbVhvcUJ1ZEwyelNUTTRQWG9LaW9iMG1TNWpEVDVFWGhtdndwb0M4a2JsT1NvQQpkWjhzNXo0UVZBbWNoOGN3czUwM09yQlliUDRyVmhuT1pTK1lUT3RFa2k4dmg3MEpWNGhneG1TaHNEeUh6QTBBCnZQQnVTNzJJS1QvOHp5YW1xdVUrd2M1VDBibGxablpNeGVkK3FRZjNHajNGRW5lWFJ3cU9uOThYNW15Q01WUEUKYXlpdmEwYURYVnJJYTVlempvaXNzRVVxQlBTRlRwWkRSWW1wNnRaV2ZCNEFUbVNrVFJHVDdQUEVOaWI4MFRIcApvWFMrdEZvVjRLZXJSQXdYblM2d2FZYnU3S1Q4Qm92U2NSa1drZ011OHRleDdGQzc2QXBBdHgzTldFRVlkbEFxCnYyamRodz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwRENDQWJpZ0F3SUJBZ0lSQUtGdUVuWTIzRUJERUM3eHJ4c1M4bVV3RFFZSktvWklodmNOQVFFTEJRQXcKQURBZ0Z3MHlNakExTWpReU1qQTBORGRhR0E4eU1UTTJNRFl5TWpFME1EUTBOMW93QURDQ0FTSXdEUVlKS29aSQpodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU9LdHJWY1h0RkRMYUxTUko2TTN0dmcrZXc0Unhqa1BHOXdiCkx2T21KUGhhR2xHS1NWZjdDRjBMMHljbzZwdnpGUTdOSkdlQncwNlNaNEJqK0FxbmNTR2FIQU9PYnR2NHlWQkIKTm9rZSt3ckY2ZzcvNy9pcHhVTkxlMDB4cEQ1eWczVmdsQ1htUWpxK1NsSVk0N1U5cHFrVHl0Z0cyV0NSMXRJWApRTk9PK1NHbG5HcWlRSHJWT3pHV1lKaE9QL3RIOW1IWVJ4NDBFMzAwalRsaGs5bzZYNXVFV3JiN0pxT2huS0NTCjVqSGtQbTRoVVRZMVI4aDRjdVJKUVErWmpQSGhiUHR1STl1Z3B5aEZWdXZjQ1RlRUw1aXJxSzRwbm80aEhRNnMKM2R3eHliYUp6azRMYVJHZTZJNTNmcG53bU9XMytWUUF5VkhsL3pnUlRXQXBjUjF4NjZrQ0F3RUFBYU5ETUVFdwpEZ1lEVlIwUEFRSC9CQVFEQWdXZ01Bd0dBMVVkRXdFQi93UUNNQUF3SVFZRFZSMFJBUUgvQkJjd0ZZSVRjMkZ0CmNHeGxMWEJ5YjJwbFkzUXRiR1ZoWmpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWh6TlBIQXVzYmtYSEN5b0kKTTByaE5BRWpwMENUUTRHdnpSbVhvcUJ1ZEwyelNUTTRQWG9LaW9iMG1TNWpEVDVFWGhtdndwb0M4a2JsT1NvQQpkWjhzNXo0UVZBbWNoOGN3czUwM09yQlliUDRyVmhuT1pTK1lUT3RFa2k4dmg3MEpWNGhneG1TaHNEeUh6QTBBCnZQQnVTNzJJS1QvOHp5YW1xdVUrd2M1VDBibGxablpNeGVkK3FRZjNHajNGRW5lWFJ3cU9uOThYNW15Q01WUEUKYXlpdmEwYURYVnJJYTVlempvaXNzRVVxQlBTRlRwWkRSWW1wNnRaV2ZCNEFUbVNrVFJHVDdQUEVOaWI4MFRIcApvWFMrdEZvVjRLZXJSQXdYblM2d2FZYnU3S1Q4Qm92U2NSa1drZ011OHRleDdGQzc2QXBBdHgzTldFRVlkbEFxCnYyamRodz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBNHEydFZ4ZTBVTXRvdEpFbm96ZTIrRDU3RGhIR09ROGIzQnN1ODZZaytGb2FVWXBKClYvc0lYUXZUSnlqcW0vTVZEczBrWjRIRFRwSm5nR1A0Q3FkeElab2NBNDV1Mi9qSlVFRTJpUjc3Q3NYcUR2L3YKK0tuRlEwdDdUVEdrUG5LRGRXQ1VKZVpDT3I1S1Voamp0VDJtcVJQSzJBYlpZSkhXMGhkQTA0NzVJYVdjYXFKQQpldFU3TVpaZ21FNC8rMGYyWWRoSEhqUVRmVFNOT1dHVDJqcGZtNFJhdHZzbW82R2NvSkxtTWVRK2JpRlJOalZICnlIaHk1RWxCRDVtTThlRnMrMjRqMjZDbktFVlc2OXdKTjRRdm1LdW9yaW1lamlFZERxemQzREhKdG9uT1RndHAKRVo3b2puZCttZkNZNWJmNVZBREpVZVgvT0JGTllDbHhIWEhycVFJREFRQUJBb0lCQUJqMlNUMXJCZGRUM3c3cgpZVE1QSXA0SnUyRmNRYmpzMmdPT0ZzaU1Ca3czRitqYzBxRFdxeUFiK2orNHVNVTlxcGI3cmtPYnZaYzhkaHRrClp0ODlleTdaR3JhbGk3MjdrdWU4bHJYWTdJcE9LeTFGci9aeE02RHFnZ1NKTCs0VWpEZHowRHl3TTZEbWJhYkcKeU9TZmltZmFIeDlVK2NFeHJqZHFpaUFDQVp0YnZVdUxKNXBiQ2tkZEhwNFJvRHhFTDVNTjdVZFB3M2xDalkvegpBRndKOFM0SVlUMXFQbjJvVGltOGZ3UFBYbTN4U3F3YlJtVTZudnI4WHhEaU1wdWozUTFodW1GNzFSSGhua1JRCnU3WE1FUm5NUllwc3A0QnJId2lONFFhWDdjVFNnbDhuK3hCelhaS0FKN0NwcHpJWFFLVHlHaVZ6bjRNMWo2VjkKZ2JhRU5GRUNnWUVBLy9yamNZa0FKZytiVXhObUJHMHJJY2JxY3BZeGZUa0FkeXVHTGkrT2phVVROV2NzTU9xbQpYemp1OGR3dll5dVlCeFg4SjEwMi9uZjVBT29JSkRsbGQxN1dMMnlpalVhVWcyYTRZLzdrN3ZpVWJ5d2oveEVtCm05dDlpKzE3T1g1dUxzTUFORDEvZWg2a0w0K3pSaDIvbFB4bFZzNm9IbDNjRmZQTGU0dXBzOFVDZ1lFQTRySTAKRzhJcndNMUxuQ1VFcTVReTVrd09zMlJsR1l2MlE5MnFrN1VvL2c0VThlS0p3ZmtENXI3cHhaSjB3QnpwSE5CeQo3WWpXclY2SnRvcm16c2RkbTBHZHZzSFkzeDF2c2R3VW85R254UENpVEMxRjNYUnhkZ212bWRvL1hZRFp4OW5aCmdLYnFuUEh5RjIwNnF3SXk5eDRVdU41N3ZnOTc0YWFTSVkyOXdwVUNnWUVBazFWN2ZjaWw3a0pEVzNDcDRsaFgKWUF5V3VyZFo2c0paVXo0WThCSnRVWGUyODZEYm5aZ2hoR05Ibkt2b0ZvTnI4SUFsN3g1RzNmWjl1cG41YjZnZApqN1JsUVV5Y3p3WFZ5ei9mVjZiSmJBWmxvUXRkK0p5TmhWMnpDRXY3QmQrUVdaZmhVVEFvWkVpb3BidG5LeTlLCkt0MlBFb1RGM1J5VzVZZTZFZlVVQ3lVQ2dZQi9oWU11Z2tHZWlWMlpEbkhjR3RldkdPWEVJQnVIRFdhUXNxYjcKeEJLMUp6SzlCcFE3bTFxSWVLaUVUV2lEa1QvSXg3RiswVlVCM1laV096aXU1Uk5RL001QnVrWEc3SVlpWlF6dgpRa2EvMENWYitMT3VhWXhSdkEwZDNObDhQYmxFWk5Xbk96NEszMGN4eW00UU9JSjI1R0wvdzVlVVNKMkZSL0E0CkU4WEZLUUtCZ0NCMmk1NWdZcXFibjQxbHlZSlNPd1hOZjh3WG5RVHRmMTVMTnJ5Yk5ud0lLYWQ5M2NDM0tQRjIKelNXbVhkWTd3VzV1TGxBaFZ1Rk4vektNa216M2x6UFBWcy9yZldnVDdVUHZPQXBDVlhhYng4NmNNb21KaktUYgo3Ymt2M1lxT1FLMk9QTnpUVU8wMUxRZE9MME8rWmlVbjkwbkJQenduRWpIZmZHcEF2QUZoCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==