apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-project-database
  labels:
    app: sample-project
    component: database

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-project
      component: database

  template:
    metadata:
      labels:
        app: sample-project
        component: database

    spec:
      containers:
        - name: mongodb-container
          image: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              value: sample-project-database
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
      
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sample-project-database-data