apiVersion: v1
kind: Service
metadata:
  name: sample-project-frontend
  labels:
    app: sample-project
    component: frontend
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: sample-project
    component: frontend
