version: 1.0
consume:
  primaryNamespace: sample-project
  rules:
    - sample-project/sample-project-leaf
    - sample-project/sample-project-database
serve:
  - namespace: sample-project
    service: sample-project-core
    ports:
      - local: 3000
        remote: 3000