apiVersion: system.codezero.io/v1alpha1
kind: DevelopmentProfile
metadata:
  name: configuration-core
spec:
  commands:
    - command: Environment
      params:
        kind: deployment
        resourceName: sample-project-core
        envFile: ./env-core.sh
        format: sh
        namespace: sample-project
        output: false
