apiVersion: system.codezero.io/v1alpha1
kind: DebugProfile
metadata:
  name: teleport-frontend
  namespace: sample-project
spec:
  commands:
    - command: Teleport
      params:
        kind: Deployment
        resourceName: sample-project-core
        namespace: sample-project
        exclude:
          - sample-project-frontend
