name: publish
on:
  push:
    branches:
      - master
      - feat/2833-arm64-builds
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@master
        with:
          files: ./docker-compose.yaml
          #push: true
        env:
          USER: latest

      - name: Test
        run: |
          docker inspect --format "{{.Architecture}}" c6oio/sample-project-core:latest