name: publish
on:
  push:
    branches:
      - master
      - feat/2833-arm64-builds
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64,linux/386

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@master
        with:
          files: ./docker-compose.yaml
          set: |
            *.platform=${{ steps.qemu.outputs.platforms }}
          #push: true
        env:
          USER: latest

      - name: Test
        run: |
          docker images
          docker inspect --format "{{.Architecture}}" sample-project-core:latest